// Generate web/src/api/generated.ts from docs/contracts/openapi.yaml.
// `--check` regenerates in memory and fails when the committed file has drifted.
import { readFile, writeFile } from "node:fs/promises";

import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";

const contract = new URL("../../../docs/contracts/openapi.yaml", import.meta.url);
const target = new URL("../../src/api/generated.ts", import.meta.url);
const banner =
  "// Generated by web/tools/openapi-gen/generate.mjs from docs/contracts/openapi.yaml.\n" +
  "// Do not edit by hand: run `pnpm --dir web run gen:api`.\n\n";

// The contract discriminates ProgressRecord on the boolean `available` (`const: false|true`).
// openapi-typescript 7.13 replaces a discriminator property with a string enum built from the
// mapping keys ("false"/"true"), which never matches the JSON boolean on the wire; emit the
// boolean literal for that injected property instead.
const INJECTED_DISCRIMINATOR = "discriminator enum property added by openapi-typescript";

function transform(schema) {
  const values = schema.enum;
  if (schema.description !== INJECTED_DISCRIMINATOR || values?.length !== 1) return undefined;
  if (values[0] !== "true" && values[0] !== "false") return undefined;
  const literal = values[0] === "true" ? ts.factory.createTrue() : ts.factory.createFalse();
  return ts.factory.createLiteralTypeNode(literal);
}

const contents = banner + astToString(await openapiTS(contract, { transform }));

if (process.argv.includes("--check")) {
  let committed = "";
  try {
    committed = await readFile(target, "utf8");
  } catch {
    committed = "";
  }
  if (committed !== contents) {
    console.error("web/src/api/generated.ts is out of date; run `pnpm --dir web run gen:api`.");
    process.exit(1);
  }
} else {
  await writeFile(target, contents);
}
